apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
    - name: host-volume
      hostPath:
        path: /var/log

  containers:
    - name: busybox-container-1
      image: busybox
      command: ["sleep", "36000"]
      volumeMounts:
        - name: host-volume
          mountPath: /worker-node-data
          readOnly: true
