apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
    - name: mav-emptydir
      emptyDir: {}

  containers:
    - name: busybox-container-1
      image: busybox
      command: ["sleep","36000"]
      volumeMounts:
        - name: mav-emptydir
          mountPath: /shared-folder
    - name: busybox-container-2
      image: busybox
      command: ["sleep","36000"]
      volumeMounts:
        - name: mav-emptydir
          mountPath: /shared-folder