apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: my-gce-disk # Name of your GCE Persistent Disk
    fsType: ext4 # Filesystem type (e.g., ext4, xfs)