apiVersion: v1
kind: Pod
metadata:
  name: ping-pod
  labels:
    app: pingpod
spec:
  containers:
    - name: ping-container
      image: busybox:latest
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: true
        capabilities:
          add: ["NET_RAW"] 
      command:
        - "ping"
        - "-c"
        - "60"
        - "google.com"
